# Generated by Django 5.1.4 on 2025-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImgHero')),
                ('genre', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Главный тайтл',
                'verbose_name_plural': 'Главные тайтлы',
            },
        ),
    ]
