# Generated by Django 5.1.4 on 2025-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blog_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
