# Generated by Django 5.1.4 on 2025-05-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hero_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
