# Generated by Django 5.1.4 on 2025-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_hero_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='transcription',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
